
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql://webfestify_user:password123@db:3306/webfestify_db
    depends_on:
      - db
    volumes:
      - .:/app
    command: python app.py

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: webfestify_db
      MYSQL_USER: webfestify_user
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: rootpassword123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: