version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Base de datos
      - MYSQLHOST=db
      - MYSQLUSER=festify_user
      - MYSQLPASSWORD=festify_password
      - MYSQLDATABASE=festify_db
      - MYSQLPORT=3306
      # Configuración de correo
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=True
      - MAIL_USERNAME=festifysoporte@gmail.com
      - MAIL_PASSWORD=vipw fzjs jxwe txru
      - MAIL_DEFAULT_SENDER=festifysoporte@gmail.com
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: festify_db
      MYSQL_USER: festify_user
      MYSQL_PASSWORD: festify_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: festify_user
      PMA_PASSWORD: festify_password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: